///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Admin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Users recording.
    /// </summary>
    [TestModule("1752aba7-77a6-44a4-9b68-5fe5f17dc533", ModuleType.Recording, 1)]
    public partial class Users : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AdminRepository repository.
        /// </summary>
        public static AdminRepository repo = AdminRepository.Instance;

        static Users instance = new Users();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Users()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Users Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKSPDMAdministrationFileVau.TitleBar1' at 841;13.", repo.SOLIDWORKSPDMAdministrationFileVau.TitleBar1Info, new RecordItemIndex(0));
            repo.SOLIDWORKSPDMAdministrationFileVau.TitleBar1.Click("841;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{F15}' with focus on 'SOLIDWORKSPDMAdministration.SOLIDWORKSPDMAdministration'.", repo.SOLIDWORKSPDMAdministration.SOLIDWORKSPDMAdministrationInfo, new RecordItemIndex(1));
            repo.SOLIDWORKSPDMAdministration.SOLIDWORKSPDMAdministration.EnsureVisible();
            Keyboard.Press("{F15}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKSPDMAdministrationFileVau.TitleBar1' at 1341;12.", repo.SOLIDWORKSPDMAdministrationFileVau.TitleBar1Info, new RecordItemIndex(2));
            repo.SOLIDWORKSPDMAdministrationFileVau.TitleBar1.Click("1341;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(3));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKSPDMAdministrationFileVau.Tree1001' at 61;693.", repo.SOLIDWORKSPDMAdministrationFileVau.Tree1001Info, new RecordItemIndex(4));
            repo.SOLIDWORKSPDMAdministrationFileVau.Tree1001.Click("61;693");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(5));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKSPDMAdministrationFileVau.Tree1001' at 83;670.", repo.SOLIDWORKSPDMAdministrationFileVau.Tree1001Info, new RecordItemIndex(6));
            repo.SOLIDWORKSPDMAdministrationFileVau.Tree1001.Click("83;670");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(7));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SOLIDWORKSPDMAdministrationFileVau.Groups' at 20;52.", repo.SOLIDWORKSPDMAdministrationFileVau.GroupsInfo, new RecordItemIndex(8));
            repo.SOLIDWORKSPDMAdministrationFileVau.Groups.DoubleClick("20;52");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 56;229.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(9));
            repo.AdminProperties.AdminProperties.Click("56;229");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 61;248.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(10));
            repo.AdminProperties.AdminProperties.Click("61;248");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 70;271.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(11));
            repo.AdminProperties.AdminProperties.Click("70;271");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 72;291.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(12));
            repo.AdminProperties.AdminProperties.Click("72;291");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 67;312.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(13));
            repo.AdminProperties.AdminProperties.Click("67;312");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 74;321.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(14));
            repo.AdminProperties.AdminProperties.Click("74;321");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 66;353.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(15));
            repo.AdminProperties.AdminProperties.Click("66;353");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 75;368.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(16));
            repo.AdminProperties.AdminProperties.Click("75;368");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 62;391.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(17));
            repo.AdminProperties.AdminProperties.Click("62;391");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 50;405.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(18));
            repo.AdminProperties.AdminProperties.Click("50;405");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 64;421.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(19));
            repo.AdminProperties.AdminProperties.Click("64;421");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 65;440.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(20));
            repo.AdminProperties.AdminProperties.Click("65;440");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 65;463.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(21));
            repo.AdminProperties.AdminProperties.Click("65;463");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 52;476.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(22));
            repo.AdminProperties.AdminProperties.Click("52;476");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 59;497.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(23));
            repo.AdminProperties.AdminProperties.Click("59;497");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AdminProperties' at 59;269.", repo.AdminProperties.AdminPropertiesInfo, new RecordItemIndex(24));
            repo.AdminProperties.AdminProperties.Click("59;269");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.PDMDatasetToSagar' at 8;13.", repo.AdminProperties.PDMDatasetToSagarInfo, new RecordItemIndex(25));
            repo.AdminProperties.PDMDatasetToSagar.Click("8;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.AssignedFolderPermissions' at 23;7.", repo.AdminProperties.AssignedFolderPermissionsInfo, new RecordItemIndex(26));
            repo.AdminProperties.AssignedFolderPermissions.Click("23;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.CKeywordTest' at 87;9.", repo.AdminProperties.CKeywordTestInfo, new RecordItemIndex(27));
            repo.AdminProperties.CKeywordTest.Click("87;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AdminProperties.ButtonOK' at 24;7.", repo.AdminProperties.ButtonOKInfo, new RecordItemIndex(28));
            repo.AdminProperties.ButtonOK.Click("24;7");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
