///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4af26312-2efa-492a-8569-8f4c350abc28")]
    public partial class MyTest2Repository : RepoGenBaseFolder
    {
        static MyTest2Repository instance = new MyTest2Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTest2Repository element repository.
        /// </summary>
        [RepositoryFolder("4af26312-2efa-492a-8569-8f4c350abc28")]
        public static MyTest2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest2Repository() 
            : base("MyTest2Repository", "/", null, 0, false, "4af26312-2efa-492a-8569-8f4c350abc28", ".\\RepositoryImages\\MyTest2Repository4af26312.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4af26312-2efa-492a-8569-8f4c350abc28")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest2RepositoryFolders
    {
    }
#pragma warning restore 0436
}
