///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Repository1 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d37eb0fd-dc42-4b5d-9986-88b005782159")]
    public partial class Repository1 : RepoGenBaseFolder
    {
        static Repository1 instance = new Repository1();
        Repository1Folders.NewAppFolderAppFolder _newappfolder;

        /// <summary>
        /// Gets the singleton class instance representing the Repository1 element repository.
        /// </summary>
        [RepositoryFolder("d37eb0fd-dc42-4b5d-9986-88b005782159")]
        public static Repository1 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Repository1() 
            : base("Repository1", "/", null, 0, false, "d37eb0fd-dc42-4b5d-9986-88b005782159", ".\\RepositoryImages\\Repository1d37eb0fd.rximgres")
        {
            _newappfolder = new Repository1Folders.NewAppFolderAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d37eb0fd-dc42-4b5d-9986-88b005782159")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The NewAppFolder folder.
        /// </summary>
        [RepositoryFolder("16866753-5bed-4b95-a2b0-4a9cf59e8d3f")]
        public virtual Repository1Folders.NewAppFolderAppFolder NewAppFolder
        {
            get { return _newappfolder; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Repository1Folders
    {
        /// <summary>
        /// The NewAppFolderAppFolder folder.
        /// </summary>
        [RepositoryFolder("16866753-5bed-4b95-a2b0-4a9cf59e8d3f")]
        public partial class NewAppFolderAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new NewAppFolder  folder.
            /// </summary>
            public NewAppFolderAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewAppFolder", "/element", parentFolder, 30000, null, false, "16866753-5bed-4b95-a2b0-4a9cf59e8d3f", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("16866753-5bed-4b95-a2b0-4a9cf59e8d3f")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("16866753-5bed-4b95-a2b0-4a9cf59e8d3f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
