///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("f5a91009-192c-4b25-a56c-3369044e2a52", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PDMRepository repository.
        /// </summary>
        public static PDMRepository repo = PDMRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKSPDMAdministration.About' at 13;10.", repo.SOLIDWORKSPDMAdministration.AboutInfo, new RecordItemIndex(0));
            repo.SOLIDWORKSPDMAdministration.About.Click("13;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=559,Height=372}) on item 'AboutSOLIDWORKSPDMAdministration.AboutSOLIDWORKSPDMAdministration'.", repo.AboutSOLIDWORKSPDMAdministration.AboutSOLIDWORKSPDMAdministrationInfo, new RecordItemIndex(1));
            Validate.ContainsImage(repo.AboutSOLIDWORKSPDMAdministration.AboutSOLIDWORKSPDMAdministrationInfo, AboutSOLIDWORKSPDMAdministration_Screenshot1, AboutSOLIDWORKSPDMAdministration_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AboutSOLIDWORKSPDMAdministration.ButtonOK' at 4;4.", repo.AboutSOLIDWORKSPDMAdministration.ButtonOKInfo, new RecordItemIndex(2));
            repo.AboutSOLIDWORKSPDMAdministration.ButtonOK.Click(new Location(ButtonOK_Screenshot1, "4;4", ButtonOK_Screenshot1_Options));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage AboutSOLIDWORKSPDMAdministration_Screenshot1
        { get { return repo.AboutSOLIDWORKSPDMAdministration.AboutSOLIDWORKSPDMAdministrationInfo.GetScreenshot1(new Rectangle(0, 0, 559, 372)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions AboutSOLIDWORKSPDMAdministration_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage ButtonOK_Screenshot1
        { get { return repo.AboutSOLIDWORKSPDMAdministration.ButtonOKInfo.GetScreenshot1(new Rectangle(23, 8, 22, 10)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions ButtonOK_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
