///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("f5a91009-192c-4b25-a56c-3369044e2a52", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PDMRepository repository.
        /// </summary>
        public static PDMRepository repo = PDMRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.Icon' at 8;13.", repo.Explorer.IconInfo, new RecordItemIndex(0));
            repo.Explorer.Icon.Click("8;13");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SOLIDWORKSPDMAdministration.KeywordTest' at 28;5.", repo.SOLIDWORKSPDMAdministration.KeywordTestInfo, new RecordItemIndex(1));
            repo.SOLIDWORKSPDMAdministration.KeywordTest.DoubleClick("28;5");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{F15}' with focus on 'SOLIDWORKSPDMLoginKeywordTest'.", repo.SOLIDWORKSPDMLoginKeywordTest.SelfInfo, new RecordItemIndex(2));
            repo.SOLIDWORKSPDMLoginKeywordTest.Self.EnsureVisible();
            Keyboard.Press("{F15}");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKSPDMLoginKeywordTest' at 416;238.", repo.SOLIDWORKSPDMLoginKeywordTest.SelfInfo, new RecordItemIndex(3));
            repo.SOLIDWORKSPDMLoginKeywordTest.Self.Click("416;238");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SOLIDWORKSPDMAdministration.About' at 15;10.", repo.SOLIDWORKSPDMAdministration.AboutInfo, new RecordItemIndex(4));
            repo.SOLIDWORKSPDMAdministration.About.Click("15;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AboutSOLIDWORKSPDMAdministration.ButtonOK' at 27;19.", repo.AboutSOLIDWORKSPDMAdministration.ButtonOKInfo, new RecordItemIndex(5));
            repo.AboutSOLIDWORKSPDMAdministration.ButtonOK.Click("27;19");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
