///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace pdm_basics
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the pdm_basicsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("958529c0-63a2-4b5d-93ca-9fa86f1ca854")]
    public partial class pdm_basicsRepository : RepoGenBaseFolder
    {
        static pdm_basicsRepository instance = new pdm_basicsRepository();

        /// <summary>
        /// Gets the singleton class instance representing the pdm_basicsRepository element repository.
        /// </summary>
        [RepositoryFolder("958529c0-63a2-4b5d-93ca-9fa86f1ca854")]
        public static pdm_basicsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public pdm_basicsRepository() 
            : base("pdm_basicsRepository", "/", null, 0, false, "958529c0-63a2-4b5d-93ca-9fa86f1ca854", ".\\RepositoryImages\\pdm_basicsRepository958529c0.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("958529c0-63a2-4b5d-93ca-9fa86f1ca854")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class pdm_basicsRepositoryFolders
    {
    }
#pragma warning restore 0436
}
